language: c
install:
    - sudo apt-get update
    - sudo apt-get -y install libtool pkg-config libexpat1-dev libxml2-dev libssl-dev dos2unix astyle
stages:
  - style
  - test
before_script:
    - ./bootstrap.sh
env:
  - CONFIGURE_OPT="--without-libxml2"
  - CONFIGURE_OPT="--with-libxml2"
  - CONFIGURE_OPT="--disable-tls --without-libxml2"
  - CONFIGURE_OPT="--disable-tls --with-libxml2"
script: ./configure ${CONFIGURE_OPT} CFLAGS="-Werror" && make && make check
jobs:
  include:
    - stage: style
      name: "Check code style"
      script: ./configure && make format && git diff --exit-code
      env:
        - CONFIGURE_OPT=""
matrix:
    fast_finish: true
